/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.adminHotel;

import exception.InputKosongException;
import java.math.BigInteger;
import model.TipeRoom;
import controller.TipeRoomControll;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import table.TableTipeRoom;
/**
 *
 * @author asus
 */
public class AdminHotelTipeRoom extends javax.swing.JFrame {

    int selectedIdTipeRoom = 0;
    TipeRoomControll tipeRoomControll = new TipeRoomControll();
    public AdminHotelTipeRoom() {
        
        initComponents();
        setComponent(false);
        EditBtn.setEnabled(false);
        DeleteBtn.setEnabled(false);
        inisialisasiTableTipeRoom();
        
    }
    
    String action = null;
    
    public void setComponent(boolean value){
        tipeKamarInput.setEnabled(value);
        kapasitasInput.setEnabled(value);
        hargaInput.setEnabled(value);
        SaveBtnTipeRoom.setEnabled(value);
        CancelBtnTipeRoom.setEnabled(value);
    }
     public void inisialisasiTableTipeRoom(){
        List<TipeRoom> data= new ArrayList<TipeRoom>();
        TableTipeRoom t = new TableTipeRoom(data);
        TabelDataTipeRoom.setModel(t);
    }
    
     public void showTipeRoomByHotel(){
        TabelDataTipeRoom.setModel(tipeRoomControll.showTipeRoomByHotel(Integer.valueOf(idHotelValueTipeRoom.getText())));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        IconLabel = new javax.swing.JLabel();
        HomePanel = new javax.swing.JPanel();
        HomeLabel = new javax.swing.JLabel();
        containerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LabelPilihHotel1 = new javax.swing.JLabel();
        idHotelValueTipeRoom = new javax.swing.JLabel();
        LabelTipeKamar1 = new javax.swing.JLabel();
        namaHotelValueTipeRoom = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PanelUtama = new javax.swing.JPanel();
        FormInputPanel = new javax.swing.JPanel();
        LabelForm = new javax.swing.JLabel();
        LabelTipeKamar = new javax.swing.JLabel();
        tipeKamarInput = new javax.swing.JTextField();
        KapasitasLabel = new javax.swing.JLabel();
        kapasitasInput = new javax.swing.JTextField();
        AddBtn = new javax.swing.JButton();
        EditBtn = new javax.swing.JButton();
        DeleteBtn = new javax.swing.JButton();
        CancelBtnTipeRoom = new javax.swing.JButton();
        SaveBtnTipeRoom = new javax.swing.JButton();
        hargaInput = new javax.swing.JTextField();
        KapasitasLabel1 = new javax.swing.JLabel();
        SearchBtn = new javax.swing.JButton();
        SearchText = new javax.swing.JTextField();
        PanelDataTipeRoom = new javax.swing.JPanel();
        LabelDataTipeRoom = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelDataTipeRoom = new javax.swing.JTable();
        lihatTipeRoomBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanel.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        HomeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeLabel.setText("Home");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 131, Short.MAX_VALUE)
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(HomeLabel)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(IconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(IconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(HomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        containerPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Tipe Room");

        LabelPilihHotel1.setText("ID Hotel : ");

        LabelTipeKamar1.setText("Nama Hotel : ");

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(LabelPilihHotel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(idHotelValueTipeRoom))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(LabelTipeKamar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaHotelValueTipeRoom)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPilihHotel1)
                    .addComponent(idHotelValueTipeRoom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTipeKamar1)
                    .addComponent(namaHotelValueTipeRoom))
                .addContainerGap())
        );

        PanelUtama.setBackground(new java.awt.Color(255, 255, 255));

        LabelForm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelForm.setText("Form Input Tipe Room");

        LabelTipeKamar.setText("Tipe Kamar");

        KapasitasLabel.setText("Kapasitas");

        AddBtn.setText("Add");
        AddBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddBtnActionPerformed(evt);
            }
        });

        EditBtn.setText("Edit");
        EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditBtnActionPerformed(evt);
            }
        });

        DeleteBtn.setText("Delete");
        DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteBtnActionPerformed(evt);
            }
        });

        CancelBtnTipeRoom.setText("Cancel");

        SaveBtnTipeRoom.setText("Save");
        SaveBtnTipeRoom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnTipeRoomActionPerformed(evt);
            }
        });

        KapasitasLabel1.setText("Harga");

        javax.swing.GroupLayout FormInputPanelLayout = new javax.swing.GroupLayout(FormInputPanel);
        FormInputPanel.setLayout(FormInputPanelLayout);
        FormInputPanelLayout.setHorizontalGroup(
            FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormInputPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(SaveBtnTipeRoom)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CancelBtnTipeRoom))
                    .addGroup(FormInputPanelLayout.createSequentialGroup()
                        .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KapasitasLabel1)
                            .addGroup(FormInputPanelLayout.createSequentialGroup()
                                .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(hargaInput)
                                    .addComponent(LabelTipeKamar, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tipeKamarInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                                    .addComponent(KapasitasLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(kapasitasInput, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AddBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(DeleteBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        FormInputPanelLayout.setVerticalGroup(
            FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelForm)
                .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormInputPanelLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddBtn)
                            .addComponent(EditBtn)
                            .addComponent(DeleteBtn)))
                    .addGroup(FormInputPanelLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(LabelTipeKamar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipeKamarInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(KapasitasLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kapasitasInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(KapasitasLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(hargaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CancelBtnTipeRoom)
                    .addComponent(SaveBtnTipeRoom))
                .addContainerGap())
        );

        SearchBtn.setBackground(new java.awt.Color(204, 204, 204));
        SearchBtn.setText("Search");

        SearchText.setBackground(new java.awt.Color(204, 204, 204));

        LabelDataTipeRoom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelDataTipeRoom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDataTipeRoom.setText("Data Tipe Room");

        TabelDataTipeRoom.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelDataTipeRoom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelDataTipeRoomMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelDataTipeRoom);

        javax.swing.GroupLayout PanelDataTipeRoomLayout = new javax.swing.GroupLayout(PanelDataTipeRoom);
        PanelDataTipeRoom.setLayout(PanelDataTipeRoomLayout);
        PanelDataTipeRoomLayout.setHorizontalGroup(
            PanelDataTipeRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelDataTipeRoom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 276, Short.MAX_VALUE)
            .addGroup(PanelDataTipeRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelDataTipeRoomLayout.setVerticalGroup(
            PanelDataTipeRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataTipeRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDataTipeRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lihatTipeRoomBtn.setText("Lihat Tipe Room");
        lihatTipeRoomBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatTipeRoomBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelUtamaLayout = new javax.swing.GroupLayout(PanelUtama);
        PanelUtama.setLayout(PanelUtamaLayout);
        PanelUtamaLayout.setHorizontalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(FormInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addComponent(SearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SearchBtn))
                    .addComponent(PanelDataTipeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lihatTipeRoomBtn))
                .addContainerGap(190, Short.MAX_VALUE))
        );
        PanelUtamaLayout.setVerticalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FormInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUtamaLayout.createSequentialGroup()
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchBtn)
                            .addComponent(SearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(lihatTipeRoomBtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PanelDataTipeRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(139, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(PanelUtama);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 872, Short.MAX_VALUE)
                    .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddBtnActionPerformed
        setComponent(true);
        action = "tambah";
    }//GEN-LAST:event_AddBtnActionPerformed

    public void inputTipeRoomKosong() throws InputKosongException{
        if(tipeKamarInput.getText().isEmpty() || kapasitasInput.getText().isEmpty()){
            throw new InputKosongException();
        }
    }
    private void SaveBtnTipeRoomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnTipeRoomActionPerformed
          try{
            inputTipeRoomKosong();
            
            String tipeKamar = tipeKamarInput.getText();
            String kapasitas = kapasitasInput.getText();
            
            
            if(action.equals("tambah")){
                TipeRoom t = new TipeRoom(0, Integer.valueOf(idHotelValueTipeRoom.getText()), tipeKamar, Integer.valueOf(kapasitas), BigInteger.valueOf(Long.valueOf(hargaInput.getText())));
                tipeRoomControll.insertDataTipeRoom(t);
                showTipeRoomByHotel();
            }else{
                TipeRoom t = new TipeRoom(selectedIdTipeRoom, Integer.valueOf(idHotelValueTipeRoom.getText()), tipeKamar, Integer.valueOf(kapasitas), BigInteger.valueOf(Long.valueOf(hargaInput.getText())));
                tipeRoomControll.updateDataTipeRoom(t);
                showTipeRoomByHotel();
                
            }
             
        }catch(InputKosongException e){
            JOptionPane.showMessageDialog(this, e.message());
        }
    }//GEN-LAST:event_SaveBtnTipeRoomActionPerformed

    private void lihatTipeRoomBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatTipeRoomBtnActionPerformed
        showTipeRoomByHotel();
    }//GEN-LAST:event_lihatTipeRoomBtnActionPerformed

    private void TabelDataTipeRoomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelDataTipeRoomMouseClicked
        
         
   
         int clickedTipeRoom = TabelDataTipeRoom.getSelectedRow();
         TableModel tableModel = TabelDataTipeRoom.getModel();
         
         
         selectedIdTipeRoom = Integer.parseInt(tableModel.getValueAt(clickedTipeRoom, 0).toString());
         String selectedNamaTipe = tableModel.getValueAt(clickedTipeRoom, 1).toString();
         String selectedKapasitas = tableModel.getValueAt(clickedTipeRoom,2).toString();
         String selectedHarga = tableModel.getValueAt(clickedTipeRoom,3).toString();
         
         tipeKamarInput.setText(selectedNamaTipe);
         kapasitasInput.setText(selectedKapasitas);
         hargaInput.setText(selectedHarga);
         
         AddBtn.setEnabled(false);
         EditBtn.setEnabled(true);
         DeleteBtn.setEnabled(true);
         
         
         
    
    }//GEN-LAST:event_TabelDataTipeRoomMouseClicked

    private void EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditBtnActionPerformed
        action = "ubah";
        setComponent(true);
    }//GEN-LAST:event_EditBtnActionPerformed

    private void DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteBtnActionPerformed
        if(!tipeKamarInput.getText().isEmpty()){
            int getAnswer = JOptionPane.showConfirmDialog(rootPane,"Apakah yakin ingin menghapus data ? ", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            switch(getAnswer){
                case 0:
                try{
                    tipeRoomControll.deleteDataTipeRoom(selectedIdTipeRoom);
                    AddBtn.setEnabled(true);
                    EditBtn.setEnabled(false);
                    DeleteBtn.setEnabled(false);
                    showTipeRoomByHotel();
                }catch(Exception e){
                    System.out.println("Error : "+e.getMessage());
                }
                break;
                case 1:
                break;
            }
        }                
    }//GEN-LAST:event_DeleteBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHotelTipeRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHotelTipeRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHotelTipeRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHotelTipeRoom.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHotelTipeRoom().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddBtn;
    private javax.swing.JButton CancelBtnTipeRoom;
    private javax.swing.JButton DeleteBtn;
    private javax.swing.JButton EditBtn;
    private javax.swing.JPanel FormInputPanel;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel IconLabel;
    private javax.swing.JLabel KapasitasLabel;
    private javax.swing.JLabel KapasitasLabel1;
    private javax.swing.JLabel LabelDataTipeRoom;
    private javax.swing.JLabel LabelForm;
    private javax.swing.JLabel LabelPilihHotel1;
    private javax.swing.JLabel LabelTipeKamar;
    private javax.swing.JLabel LabelTipeKamar1;
    private javax.swing.JPanel PanelDataTipeRoom;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JButton SaveBtnTipeRoom;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchText;
    private javax.swing.JTable TabelDataTipeRoom;
    private javax.swing.JPanel containerPanel;
    private javax.swing.JTextField hargaInput;
    public javax.swing.JLabel idHotelValueTipeRoom;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField kapasitasInput;
    private javax.swing.JButton lihatTipeRoomBtn;
    public javax.swing.JLabel namaHotelValueTipeRoom;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTextField tipeKamarInput;
    // End of variables declaration//GEN-END:variables
}
