/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.adminHotel;

import java.util.ArrayList;
import java.util.List;
import model.Hotel;
import table.TableHotel;
import controller.HotelControll;
import controller.PemesananControll;
import javax.swing.table.TableModel;

/**
 *
 * @author asus
 */
public class AdminHotelPemesanan extends javax.swing.JFrame {

    HotelControll hotelControl = new HotelControll();
    PemesananControll pemesananControl = new PemesananControll();
    
    int selectedIdHotel = 0;
    int selectedIdPemesanan = 0;
    /**
     * Creates new form AdminHotel_TipeRoom
     */
    public AdminHotelPemesanan() {
        initComponents();
        inisialisasiHotelTable();
        namaShow.setEnabled(false);
        noHandphoneShow.setEnabled(false);
        emailShow.setEnabled(false);
    }
    
    

    public void inisialisasiHotelTable(){
        
        List<Hotel> data = new ArrayList<Hotel>();
        TableHotel t = new TableHotel(data);
        tableHotelInPemesanan.setModel(t);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        IconLabel = new javax.swing.JLabel();
        TipeRoomPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PemesananPanel = new javax.swing.JPanel();
        LabelPemesanan = new javax.swing.JLabel();
        HomePanel = new javax.swing.JPanel();
        HomeLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PanelUtama = new javax.swing.JPanel();
        SearchBtn = new javax.swing.JButton();
        SearchText = new javax.swing.JTextField();
        LabelPilihHotel = new javax.swing.JLabel();
        TotalPendapatanLabel = new javax.swing.JLabel();
        totalPendapatanInput = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableHotelInPemesanan = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableListPemesanan = new javax.swing.JTable();
        LabelPilihHotel1 = new javax.swing.JLabel();
        idHotelAdminValuePemesanan = new javax.swing.JLabel();
        tampilHotel = new javax.swing.JButton();
        namaShow = new javax.swing.JTextField();
        TotalPendapatanLabel1 = new javax.swing.JLabel();
        noHandphoneShow = new javax.swing.JTextField();
        TotalPendapatanLabel2 = new javax.swing.JLabel();
        TotalPendapatanLabel3 = new javax.swing.JLabel();
        emailShow = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanel.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Tipe Room");
        jLabel1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout TipeRoomPanelLayout = new javax.swing.GroupLayout(TipeRoomPanel);
        TipeRoomPanel.setLayout(TipeRoomPanelLayout);
        TipeRoomPanelLayout.setHorizontalGroup(
            TipeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        TipeRoomPanelLayout.setVerticalGroup(
            TipeRoomPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TipeRoomPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        PemesananPanel.setBackground(new java.awt.Color(255, 255, 255));

        LabelPemesanan.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LabelPemesanan.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelPemesanan.setText("Pemesanan");

        javax.swing.GroupLayout PemesananPanelLayout = new javax.swing.GroupLayout(PemesananPanel);
        PemesananPanel.setLayout(PemesananPanelLayout);
        PemesananPanelLayout.setHorizontalGroup(
            PemesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelPemesanan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
        );
        PemesananPanelLayout.setVerticalGroup(
            PemesananPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PemesananPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(LabelPemesanan)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        HomeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeLabel.setText("Home");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(HomeLabel)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TipeRoomPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PemesananPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(HomePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(IconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(IconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(TipeRoomPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(PemesananPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 85, Short.MAX_VALUE))
        );

        PanelUtama.setBackground(new java.awt.Color(255, 255, 255));

        SearchBtn.setBackground(new java.awt.Color(204, 204, 204));
        SearchBtn.setText("Search");

        SearchText.setBackground(new java.awt.Color(204, 204, 204));

        LabelPilihHotel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelPilihHotel.setText("Pilih Hotel");

        TotalPendapatanLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TotalPendapatanLabel.setText("Total Pendapatan : ");

        totalPendapatanInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalPendapatanInputActionPerformed(evt);
            }
        });

        tableHotelInPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        tableHotelInPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableHotelInPemesananMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableHotelInPemesanan);

        tableListPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableListPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableListPemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableListPemesanan);

        LabelPilihHotel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelPilihHotel1.setText("ID Hotel Admin : ");

        idHotelAdminValuePemesanan.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        tampilHotel.setText("Tampilkan Hotel Milikmu");
        tampilHotel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tampilHotelMouseClicked(evt);
            }
        });
        tampilHotel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tampilHotelActionPerformed(evt);
            }
        });

        namaShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaShowActionPerformed(evt);
            }
        });

        TotalPendapatanLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TotalPendapatanLabel1.setText("Nama");

        noHandphoneShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noHandphoneShowActionPerformed(evt);
            }
        });

        TotalPendapatanLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TotalPendapatanLabel2.setText("No Handphone");

        TotalPendapatanLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TotalPendapatanLabel3.setText("Email");

        emailShow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailShowActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelUtamaLayout = new javax.swing.GroupLayout(PanelUtama);
        PanelUtama.setLayout(PanelUtamaLayout);
        PanelUtamaLayout.setHorizontalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUtamaLayout.createSequentialGroup()
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelPilihHotel)
                            .addGroup(PanelUtamaLayout.createSequentialGroup()
                                .addComponent(LabelPilihHotel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(idHotelAdminValuePemesanan)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TotalPendapatanLabel)
                            .addComponent(totalPendapatanInput, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tampilHotel, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TotalPendapatanLabel3)
                    .addComponent(emailShow, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUtamaLayout.createSequentialGroup()
                            .addComponent(SearchText)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(TotalPendapatanLabel1)
                    .addComponent(namaShow, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TotalPendapatanLabel2)
                    .addComponent(noHandphoneShow, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(71, 71, 71))
        );
        PanelUtamaLayout.setVerticalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchBtn)
                            .addComponent(SearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, PanelUtamaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(LabelPilihHotel1)
                            .addComponent(idHotelAdminValuePemesanan))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(LabelPilihHotel)
                .addGap(51, 51, 51)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addComponent(TotalPendapatanLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(totalPendapatanInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(tampilHotel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(TotalPendapatanLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TotalPendapatanLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(noHandphoneShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(TotalPendapatanLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emailShow, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(299, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(PanelUtama);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 794, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void totalPendapatanInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalPendapatanInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalPendapatanInputActionPerformed

    public void showHotel(){
//        tableTipeRoomPembayaran.setModel(tipeRoomControl.showTipeRoomByHotel(Integer.valueOf(idHotelValuePembayaran.getText())));
       tableHotelInPemesanan.setModel(hotelControl.showHotelByHotelAdmin(Integer.valueOf(idHotelAdminValuePemesanan.getText())));
    }
    
    private void tampilHotelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tampilHotelMouseClicked
        showHotel();
    }//GEN-LAST:event_tampilHotelMouseClicked

    private void tableHotelInPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableHotelInPemesananMouseClicked
        int clickedHotel = tableHotelInPemesanan.getSelectedRow();
        TableModel tableModel = tableHotelInPemesanan.getModel();
        selectedIdHotel = Integer.parseInt(tableModel.getValueAt(clickedHotel, 1).toString());
        totalPendapatanInput.setText(""+pemesananControl.countPendapatanByIdHotel(selectedIdHotel));
        tableListPemesanan.setModel(pemesananControl.showPemesananByIdHotel(selectedIdHotel));
        
    }//GEN-LAST:event_tableHotelInPemesananMouseClicked

    private void namaShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaShowActionPerformed

    private void noHandphoneShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noHandphoneShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noHandphoneShowActionPerformed

    private void emailShowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailShowActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailShowActionPerformed

    private void tableListPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableListPemesananMouseClicked
        int clickedHotel = tableListPemesanan.getSelectedRow();
        TableModel tableModel = tableListPemesanan.getModel();
        
        selectedIdPemesanan = Integer.parseInt(tableModel.getValueAt(clickedHotel, 0).toString());
        
        namaShow.setText(pemesananControl.detailPemesanan(selectedIdPemesanan).get(0).getNamaLengkap());
        noHandphoneShow.setText(pemesananControl.detailPemesanan(selectedIdPemesanan).get(0).getNoHandphone());
        emailShow.setText(pemesananControl.detailPemesanan(selectedIdPemesanan).get(0).getEmail());
    }//GEN-LAST:event_tableListPemesananMouseClicked

    private void tampilHotelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tampilHotelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tampilHotelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHotelPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHotelPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHotelPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHotelPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHotelPemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JLabel IconLabel;
    private javax.swing.JLabel LabelPemesanan;
    private javax.swing.JLabel LabelPilihHotel;
    private javax.swing.JLabel LabelPilihHotel1;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JPanel PemesananPanel;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchText;
    private javax.swing.JPanel TipeRoomPanel;
    private javax.swing.JLabel TotalPendapatanLabel;
    private javax.swing.JLabel TotalPendapatanLabel1;
    private javax.swing.JLabel TotalPendapatanLabel2;
    private javax.swing.JLabel TotalPendapatanLabel3;
    private javax.swing.JTextField emailShow;
    public javax.swing.JLabel idHotelAdminValuePemesanan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField namaShow;
    private javax.swing.JTextField noHandphoneShow;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tableHotelInPemesanan;
    private javax.swing.JTable tableListPemesanan;
    private javax.swing.JButton tampilHotel;
    private javax.swing.JTextField totalPendapatanInput;
    // End of variables declaration//GEN-END:variables
}
