/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.user;

import controller.GradeControll;
import controller.HotelControll;
import controller.PemesananControll;
import controller.ProvinsiControll;
import controller.SubFasilitasControl;
import view.adminHotel.*;
import exception.InputKosongException;
import java.math.BigInteger;
import model.TipeRoom;
import controller.TipeRoomControll;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Pemesanan;
import table.TablePemesanan;
import table.TableTipeRoom;
import controller.TipeRoomControll;
import controller.UserControll;
/**
 *
 * @author asus
 */
public class UserPemesanan extends javax.swing.JFrame {

    int selectedIdPemesanan = 0;
    TipeRoomControll tipeRoomControll = new TipeRoomControll();
    PemesananControll pemesananControl = new PemesananControll();
    HotelControll hotelControl = new HotelControll();
    GradeControll gradeControl = new GradeControll();
    ProvinsiControll provinsiControl = new ProvinsiControll();
    SubFasilitasControl subControl = new SubFasilitasControl();
    UserControll userControl = new UserControll();
    
    
    public UserPemesanan() {
        
        initComponents();
        setComponent(false);
//        EditBtn.setEnabled(false);
//        DeleteBtn.setEnabled(false);
        inisiasiTablePemesanan();
        
    }
    
    String action = null;
    
    public void setComponent(boolean value){
        namaHotelInput.setEnabled(value);
        gradeInput.setEnabled(value);
        locationInput.setEnabled(value);
//        SaveBtnTipeRoom.setEnabled(value);
//        CancelBtnTipeRoom.setEnabled(value);
    }
     public void inisiasiTablePemesanan(){
        List<Pemesanan> data= new ArrayList<Pemesanan>();
        TablePemesanan t = new TablePemesanan(data);
        tableDataPemesanan.setModel(t);
    }
    
     public void showPemesananByUser(){
//         TabelListPemesanan table = 
            tableDataPemesanan.setModel(pemesananControl.showPemesananByIdUser(Integer.valueOf(idUserInputInPemesananUser.getText())));
//        TabelDataTipeRoom.setModel(tipeRoomControll.showTipeRoomByHotel(Integer.valueOf(idHotelValueTipeRoom.getText())));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        IconLabel = new javax.swing.JLabel();
        HomePanel = new javax.swing.JPanel();
        HomeLabel = new javax.swing.JLabel();
        HomePanel1 = new javax.swing.JPanel();
        HomeLabel1 = new javax.swing.JLabel();
        HomePanel2 = new javax.swing.JPanel();
        HomeLabel2 = new javax.swing.JLabel();
        containerPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        LabelPilihHotel1 = new javax.swing.JLabel();
        LabelTipeKamar1 = new javax.swing.JLabel();
        idUserInputInPemesananUser = new javax.swing.JLabel();
        usernameInput = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        PanelUtama = new javax.swing.JPanel();
        FormInputPanel = new javax.swing.JPanel();
        LabelForm = new javax.swing.JLabel();
        LabelTipeKamar = new javax.swing.JLabel();
        namaHotelInput = new javax.swing.JTextField();
        KapasitasLabel = new javax.swing.JLabel();
        gradeInput = new javax.swing.JTextField();
        locationInput = new javax.swing.JTextField();
        KapasitasLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        detailLokasiInput = new javax.swing.JLabel();
        KapasitasLabel2 = new javax.swing.JLabel();
        checkinDate = new javax.swing.JTextField();
        KapasitasLabel3 = new javax.swing.JLabel();
        KapasitasLabel4 = new javax.swing.JLabel();
        checkoutDate = new javax.swing.JTextField();
        checkinTime = new javax.swing.JTextField();
        checkoutTime = new javax.swing.JTextField();
        tipeKamar = new javax.swing.JTextField();
        LabelTipeKamar2 = new javax.swing.JLabel();
        LabelTipeKamar3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableFasilitas = new javax.swing.JTable();
        LabelTipeKamar4 = new javax.swing.JLabel();
        hargaInput = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        SearchText = new javax.swing.JTextField();
        PanelDataTipeRoom = new javax.swing.JPanel();
        LabelDataTipeRoom = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDataPemesanan = new javax.swing.JTable();
        lihatDataPemesanan = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sidePanel.setBackground(new java.awt.Color(255, 255, 255));
        sidePanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        HomePanel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomePanelMouseClicked(evt);
            }
        });

        HomeLabel.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HomeLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeLabel.setText("Home");

        javax.swing.GroupLayout HomePanelLayout = new javax.swing.GroupLayout(HomePanel);
        HomePanel.setLayout(HomePanelLayout);
        HomePanelLayout.setHorizontalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        HomePanelLayout.setVerticalGroup(
            HomePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(HomeLabel)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        HomePanel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomePanel1MouseClicked(evt);
            }
        });

        HomeLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HomeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeLabel1.setText("Profile");

        javax.swing.GroupLayout HomePanel1Layout = new javax.swing.GroupLayout(HomePanel1);
        HomePanel1.setLayout(HomePanel1Layout);
        HomePanel1Layout.setHorizontalGroup(
            HomePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomePanel1Layout.setVerticalGroup(
            HomePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanel1Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(HomeLabel1)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        HomePanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                HomePanel2MouseClicked(evt);
            }
        });

        HomeLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        HomeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        HomeLabel2.setText("Pemesanan");

        javax.swing.GroupLayout HomePanel2Layout = new javax.swing.GroupLayout(HomePanel2);
        HomePanel2.setLayout(HomePanel2Layout);
        HomePanel2Layout.setHorizontalGroup(
            HomePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(HomeLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        HomePanel2Layout.setVerticalGroup(
            HomePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomePanel2Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(HomeLabel2)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout sidePanelLayout = new javax.swing.GroupLayout(sidePanel);
        sidePanel.setLayout(sidePanelLayout);
        sidePanelLayout.setHorizontalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(IconLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                .addComponent(HomePanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(HomePanel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(HomePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        sidePanelLayout.setVerticalGroup(
            sidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidePanelLayout.createSequentialGroup()
                .addComponent(IconLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(HomePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HomePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HomePanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        containerPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pemesanan User");

        LabelPilihHotel1.setText("ID User : ");

        LabelTipeKamar1.setText("Username : ");

        idUserInputInPemesananUser.setText("ID User : ");

        usernameInput.setText("ID User : ");

        javax.swing.GroupLayout containerPanelLayout = new javax.swing.GroupLayout(containerPanel);
        containerPanel.setLayout(containerPanelLayout);
        containerPanelLayout.setHorizontalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 1101, Short.MAX_VALUE)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(LabelPilihHotel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(idUserInputInPemesananUser))
                    .addGroup(containerPanelLayout.createSequentialGroup()
                        .addComponent(LabelTipeKamar1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(usernameInput)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        containerPanelLayout.setVerticalGroup(
            containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(containerPanelLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelPilihHotel1)
                    .addComponent(idUserInputInPemesananUser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(containerPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelTipeKamar1)
                    .addComponent(usernameInput))
                .addContainerGap())
        );

        PanelUtama.setBackground(new java.awt.Color(255, 255, 255));

        LabelForm.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        LabelForm.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelForm.setText("Detail Pemesanan");

        LabelTipeKamar.setText("Hotel");

        KapasitasLabel.setText("Grade");

        KapasitasLabel1.setText("Location");

        detailLokasiInput.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        detailLokasiInput.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        jScrollPane3.setViewportView(detailLokasiInput);

        KapasitasLabel2.setText("Detail Lokasi");

        KapasitasLabel3.setText("checkin");

        KapasitasLabel4.setText("checkout");

        LabelTipeKamar2.setText("Room Type");

        LabelTipeKamar3.setText("Fasilitas");

        tableFasilitas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableFasilitas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableFasilitasMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tableFasilitas);

        LabelTipeKamar4.setText("Harga");

        javax.swing.GroupLayout FormInputPanelLayout = new javax.swing.GroupLayout(FormInputPanel);
        FormInputPanel.setLayout(FormInputPanelLayout);
        FormInputPanelLayout.setHorizontalGroup(
            FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelForm, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(FormInputPanelLayout.createSequentialGroup()
                        .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(KapasitasLabel3)
                            .addComponent(checkinDate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkinTime, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(KapasitasLabel1)
                    .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(locationInput)
                        .addComponent(LabelTipeKamar, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(namaHotelInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 160, Short.MAX_VALUE)
                        .addComponent(KapasitasLabel, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(gradeInput, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(KapasitasLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(KapasitasLabel4)
                    .addGroup(FormInputPanelLayout.createSequentialGroup()
                        .addComponent(checkoutDate, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkoutTime, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(LabelTipeKamar2)
                    .addComponent(tipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabelTipeKamar3)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(LabelTipeKamar4)
                    .addComponent(hargaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        FormInputPanelLayout.setVerticalGroup(
            FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(FormInputPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelForm)
                .addGap(36, 36, 36)
                .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(FormInputPanelLayout.createSequentialGroup()
                        .addComponent(LabelTipeKamar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(namaHotelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormInputPanelLayout.createSequentialGroup()
                        .addComponent(LabelTipeKamar2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tipeKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KapasitasLabel)
                    .addComponent(LabelTipeKamar3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(FormInputPanelLayout.createSequentialGroup()
                        .addComponent(gradeInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(KapasitasLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(locationInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20)
                        .addComponent(KapasitasLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(FormInputPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelTipeKamar4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hargaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormInputPanelLayout.createSequentialGroup()
                        .addComponent(KapasitasLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(checkinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, FormInputPanelLayout.createSequentialGroup()
                        .addComponent(KapasitasLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(FormInputPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(checkoutDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkinTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(checkoutTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        SearchBtn.setBackground(new java.awt.Color(204, 204, 204));
        SearchBtn.setText("Search");

        SearchText.setBackground(new java.awt.Color(204, 204, 204));

        LabelDataTipeRoom.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LabelDataTipeRoom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LabelDataTipeRoom.setText("Data Pemesanan");

        tableDataPemesanan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableDataPemesanan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDataPemesananMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDataPemesanan);

        javax.swing.GroupLayout PanelDataTipeRoomLayout = new javax.swing.GroupLayout(PanelDataTipeRoom);
        PanelDataTipeRoom.setLayout(PanelDataTipeRoomLayout);
        PanelDataTipeRoomLayout.setHorizontalGroup(
            PanelDataTipeRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LabelDataTipeRoom, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(PanelDataTipeRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
                .addContainerGap())
        );
        PanelDataTipeRoomLayout.setVerticalGroup(
            PanelDataTipeRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelDataTipeRoomLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LabelDataTipeRoom)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lihatDataPemesanan.setText("Lihat data pemesanan");
        lihatDataPemesanan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lihatDataPemesananActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelUtamaLayout = new javax.swing.GroupLayout(PanelUtama);
        PanelUtama.setLayout(PanelUtamaLayout);
        PanelUtamaLayout.setHorizontalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(FormInputPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PanelDataTipeRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(PanelUtamaLayout.createSequentialGroup()
                                .addComponent(SearchText, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(SearchBtn))
                            .addComponent(lihatDataPemesanan, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        PanelUtamaLayout.setVerticalGroup(
            PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelUtamaLayout.createSequentialGroup()
                .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelUtamaLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addGroup(PanelUtamaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SearchBtn)
                            .addComponent(SearchText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(lihatDataPemesanan)
                        .addGap(8, 8, 8)
                        .addComponent(PanelDataTipeRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(FormInputPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jScrollPane2.setViewportView(PanelUtama);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(sidePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(containerPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1093, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(sidePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(containerPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void inputTipeRoomKosong() throws InputKosongException{
        if(namaHotelInput.getText().isEmpty() || gradeInput.getText().isEmpty()){
            throw new InputKosongException();
        }
    }
    private void tableDataPemesananMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDataPemesananMouseClicked
        
         
   
         int clickedTipeRoom = tableDataPemesanan.getSelectedRow();
         TableModel tableModel = tableDataPemesanan.getModel();
         
         
         selectedIdPemesanan = Integer.parseInt(tableModel.getValueAt(clickedTipeRoom, 0).toString());

         String selectedNamaHotel = tableModel.getValueAt(clickedTipeRoom, 1).toString();
         
         
         namaHotelInput.setText(hotelControl.detailHotel(Integer.valueOf(selectedNamaHotel)).get(0).getNamaHotel());
         gradeInput.setText(gradeControl.getGrade(hotelControl.detailHotel(Integer.valueOf(selectedNamaHotel)).get(0).getId_grade()));
         locationInput.setText(provinsiControl.getLokasi(hotelControl.detailHotel(Integer.valueOf(selectedNamaHotel)).get(0).getId_provinsi()));
         detailLokasiInput.setText(hotelControl.detailHotel(Integer.valueOf(selectedNamaHotel)).get(0).getDetailLokasi());
         checkinDate.setText(pemesananControl.detailPemesanan(selectedIdPemesanan).get(0).getTanggalCheckin());
         checkoutDate.setText(pemesananControl.detailPemesanan(selectedIdPemesanan).get(0).getTanggalCheckout());
         tipeKamar.setText(tipeRoomControll.getTipeRoom(pemesananControl.detailPemesanan(selectedIdPemesanan).get(0).getId_tipe_room()));
         hargaInput.setText(pemesananControl.detailPemesanan(selectedIdPemesanan).get(0).getPembayaran().toString());
         tableFasilitas.setModel(subControl.showSubFasilitasByHotel(Integer.valueOf(selectedNamaHotel)));
//         tableHotelInPemesanan.setModel(hotelControl.showHotelByHotelAdmin(Integer.valueOf(idHotelAdminValuePemesanan.getText())));
         
    
    }//GEN-LAST:event_tableDataPemesananMouseClicked

    private void tableFasilitasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableFasilitasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableFasilitasMouseClicked

    private void lihatDataPemesananActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lihatDataPemesananActionPerformed
        showPemesananByUser();
    }//GEN-LAST:event_lihatDataPemesananActionPerformed

    private void HomePanelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePanelMouseClicked
        // TODO add your handling code here:

        UserHome u = new UserHome();
        this.dispose();
        u.setVisible(true);
        u.idUserHomeValue.setText(idUserInputInPemesananUser.getText());
    }//GEN-LAST:event_HomePanelMouseClicked

    private void HomePanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePanel2MouseClicked
   
        
    }//GEN-LAST:event_HomePanel2MouseClicked

    private void HomePanel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HomePanel1MouseClicked
         this.dispose();
         UserProfile u = new UserProfile();
         u.setVisible(true);
         u.idUserProfile.setText(idUserInputInPemesananUser.getText());
         u.saldoInput.setText(""+userControl.getSaldo(Integer.valueOf(idUserInputInPemesananUser.getText())));
    }//GEN-LAST:event_HomePanel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserPemesanan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserPemesanan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel FormInputPanel;
    private javax.swing.JLabel HomeLabel;
    private javax.swing.JLabel HomeLabel1;
    private javax.swing.JLabel HomeLabel2;
    private javax.swing.JPanel HomePanel;
    private javax.swing.JPanel HomePanel1;
    private javax.swing.JPanel HomePanel2;
    private javax.swing.JLabel IconLabel;
    private javax.swing.JLabel KapasitasLabel;
    private javax.swing.JLabel KapasitasLabel1;
    private javax.swing.JLabel KapasitasLabel2;
    private javax.swing.JLabel KapasitasLabel3;
    private javax.swing.JLabel KapasitasLabel4;
    private javax.swing.JLabel LabelDataTipeRoom;
    private javax.swing.JLabel LabelForm;
    private javax.swing.JLabel LabelPilihHotel1;
    private javax.swing.JLabel LabelTipeKamar;
    private javax.swing.JLabel LabelTipeKamar1;
    private javax.swing.JLabel LabelTipeKamar2;
    private javax.swing.JLabel LabelTipeKamar3;
    private javax.swing.JLabel LabelTipeKamar4;
    private javax.swing.JPanel PanelDataTipeRoom;
    private javax.swing.JPanel PanelUtama;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JTextField SearchText;
    private javax.swing.JTextField checkinDate;
    private javax.swing.JTextField checkinTime;
    private javax.swing.JTextField checkoutDate;
    private javax.swing.JTextField checkoutTime;
    private javax.swing.JPanel containerPanel;
    public javax.swing.JLabel detailLokasiInput;
    private javax.swing.JTextField gradeInput;
    private javax.swing.JTextField hargaInput;
    public javax.swing.JLabel idUserInputInPemesananUser;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JButton lihatDataPemesanan;
    private javax.swing.JTextField locationInput;
    private javax.swing.JTextField namaHotelInput;
    private javax.swing.JPanel sidePanel;
    private javax.swing.JTable tableDataPemesanan;
    private javax.swing.JTable tableFasilitas;
    private javax.swing.JTextField tipeKamar;
    public javax.swing.JLabel usernameInput;
    // End of variables declaration//GEN-END:variables
}
